name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        python-version: ['3.4', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.x', 'pypy-3.6']
        include:
          - os: ubuntu-20.04
            python-version: '2.7'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      if: matrix.python-version != '2.7'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python 2.7
      if: matrix.python-version == '2.7'
      run: |
        sudo apt-get update
        sudo apt-get install -y python2

    - name: Run tests
      run: |
        set -e
        python ./setconf.py --test
        cd testcases && ./test.sh
